language: node_js

node_js:
  - "0.10"
  - "0.11"

addons:
   firefox: "31.0"
   selenium: "2.41"

services:
  - selenium

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - firefox --version



branches:
 only:
   - master


archive: true
#cache: true 
