language: node_js

node_js:
  #- "0.10"
  - "0.11"
  #- "0.12"

addons:
   firefox: "39.0"
   selenium: "2.42"

build_image: drydock/u14nodpls:tip

services:
  - selenium

script:
 - xvfb-run --server-args="-ac" npm test

archive: true
#cache: true 
#services:
 #  - selenium
