language: node_js

node_js:
  - "0.10"
  #- "0.11"

addons:
   firefox: "24.0"

services:
  - selenium

before_script:
  - "export DISPLAY=:99.0"
  - "/etc/init.d/xvfb start"
  - firefox --version

after_script:
  - "/etc/init.d/xvfb stop"
  

branches:
 only:
   - master

notifications:
  email: vidya@shippable.com
